baseURL = 'https://nicovaras.github.io/'
languageCode = 'en-us'
title = "Sir Gradient's Descent into Madness"
title2 = 'The Count of Data Cristo'
theme = 'hugo-blog-awesome'
publishDir = "docs"

googleAnalytics = '' # G-MEASUREMENT_ID
enableEmoji = true


[params]
  sitename = "Sir Gradient's Descent into Madness"
  defaultColor = "dark" # set default color mode: dark or light
  description = "Exploring the intricacies of Machine Learning and unraveling the mysteries of Data Science, one algorithm at a time."


[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20

[params.author]
  avatar = "gd.jpeg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Sir Gradient's Descent into Madness"
  name = "Nico Varas"
  description = "Exploring the intricacies of Machine Learning and Data Science, one algorithm at a time."

[[params.socialIcons]]
name = "github"
url = "https://github.com/nicovaras"